/// Creates the questions
struct QuestionProvider {
    let question: String
    let answerOptions: [String]
    let correctAnswer: Int
}

/// Holds all the questions in the quiz (20 Questions)
struct Quiz {
    let questions: [QuestionProvider] = [
        QuestionProvider(question: "Norvasc",
                         answerOptions: ["Amlodipine","Montelukast","Prednisone"],
                         correctAnswer: 0),
        QuestionProvider(question: "Zestril",
                         answerOptions: ["Lisinopril" ,"Enalapril","Valsartan"],
                         correctAnswer: 0),
        QuestionProvider(question: "Vasotec",
                         answerOptions: ["Pravastatin","Enalapril","Valsartan"],
                         correctAnswer: 1),
        QuestionProvider(question: "Altace",
                         answerOptions: ["Rosuvastatin","Simvastatin","Ramipril"],
                         correctAnswer: 2),
        QuestionProvider(question: "Cozaar",
                         answerOptions: ["Losartan","Alprazolam","Lisinopril"],
                         correctAnswer: 0),
        QuestionProvider(question: "Benicar",
                         answerOptions: ["Omeprazole","Olmesartan","Valsartan"],
                         correctAnswer: 1),
        QuestionProvider(question: "Diovan",
                         answerOptions: ["Metformin","Sertraline","Valsartan"],
                         correctAnswer: 2),
        QuestionProvider(question: "Pravachol",
                         answerOptions:["Fenofibrate","Pravastatin","Amlodipine"],
                         correctAnswer: 1),
        QuestionProvider(question: "Zocor",
                         answerOptions: ["Simvastatin","Sertraline","Losartan"],
                         correctAnswer: 0),
        QuestionProvider(question: "Xanax",
                         answerOptions:["Amlodipine","Montelukast","Alprazolam","Escitalopram"],
                         correctAnswer: 2),
        QuestionProvider(question: "Glucophage",
                         answerOptions:["Ibuprofen","Citalopram","Albuterol","Metformin"],
                         correctAnswer: 3),
        QuestionProvider(question: "Lipitor",
                         answerOptions:["Ibuprofen","Atorvastatin","Cephalexin","Cyclobenzaprine"],
                         correctAnswer: 1),
        QuestionProvider(question: "Prilosec",
                         answerOptions:["Ibuprofen","Omeprazole","Cephalexin","Cyclobenzaprine"],
                         correctAnswer: 1),
        QuestionProvider(question: "Augmentin",
                         answerOptions:["Clonazepam","Lorazepam","Cephalexin","Amoxicillin + Clavulanate"],
                         correctAnswer: 3),
        QuestionProvider(question: "Tenormin",
                         answerOptions:["Atenolol","Xanax", "Glucophage", "Lipitor"],
                         correctAnswer: 0),
        QuestionProvider(question: "Lasix",
                         answerOptions:["Sertraline","Lipitor", "Furosemide", "metoprolol"],
                         correctAnswer: 2),
        QuestionProvider(question: "Lopressor",
                         answerOptions:["metoprolol","Montelukast","Prednisone","Escitalopram"],
                         correctAnswer: 0),
        QuestionProvider(question: "Zoloft",
                         answerOptions:["Alprazolam", "Metformin", "Atorvastatin","Sertraline"],
                         correctAnswer: 3),
        QuestionProvider(question: "Coumadin",
                         answerOptions: ["Atorvastatin","Warfarin","Hydrochlorothiazide","Furosemide"],
                         correctAnswer: 1),
        QuestionProvider(question: "Aldactone",
                         answerOptions: ["Simvastatin","Ramipril","Sertraline","Spironolactone"],
                         correctAnswer: 3)]
}
